services:
  - type: web
    name: ilynect-backend
    env: node
    region: oregon  
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: ADMIN_EMAIL
        sync: false
      - key: JWT_SECRET  
        generateValue: true
      - key: GROQ_API_KEY
        sync: false